name: ci auto rerun failed jobs
description: ci auto rerun failed jobs

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Run the sh-checker
      shell: bash
      uses: luizm/action-sh-checker@v0.9.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SHELLCHECK_OPTS: -e SC2034,SC1091
        SHFMT_OPTS: -ci -sr -i 0
      with:
        sh_checker_comment: true
        sh_checker_exclude: ""

    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Check GitHub Action workflows
      shell: bash {0}
      run: |
        pip install zizmor

        zizmor="$(zizmor . --gh-token "${{ github.token }}")"
        exit_code="$?"

        printf '%s\n' "$zizmor"

        printf '%b\n' "\`\`\`" >> $GITHUB_STEP_SUMMARY
        printf '%s\n' "$zizmor" >> $GITHUB_STEP_SUMMARY
        printf '%b' "\`\`\`" >> $GITHUB_STEP_SUMMARY

        exit "$exit_code"

    - uses: actions/checkout@v4
      shell: bash
      with:
        persist-credentials: false

    - name: editorconfig-checker
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        curl -Lo- "https://github.com/editorconfig-checker/editorconfig-checker/releases/latest/download/ec-linux-amd64.tar.gz" | tar xzf - --strip-components=1

        printf '%b\n' "\`\`\`" >> $GITHUB_STEP_SUMMARY
        ./ec-linux-amd64 --exclude '^(docs/.*|patches/.*)$' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" >> $GITHUB_STEP_SUMMARY
        exit_code=("${PIPESTATUS[0]}")
        printf '%b' "\`\`\`" >> $GITHUB_STEP_SUMMARY

        # exit "${exit_code}"
