name: qBitorrent build and release v3
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [qbittorrent, qbittorrent-nox]
        os_id: [debian, ubuntu]
        arch: [i386, amd64, arm32v7, arm64v8, ppc64le, s390x]
        include:
          - arch: i386
            docker_arch: linux/i386
            os_id: debian
            os_version_id: bullseye
            desktop_gui: ""
          - arch: i386
            docker_arch: linux/i386
            os_id: debian
            os_version_id: bullseye
            desktop_gui: -D GUI=OFF

          - arch: amd64
            docker_arch: linux/amd64
            desktop_gui: ""
          - arch: amd64
            docker_arch: linux/amd64
            desktop_gui: -D GUI=OFF

          - arch: arm32v7
            docker_arch: linux/arm/v7
            desktop_gui: ""
          - arch: arm32v7
            docker_arch: linux/arm/v7
            desktop_gui: -D GUI=OFF

          - arch: arm64v8
            docker_arch: linux/arm64
            desktop_gui: ""
          - arch: arm64v8
            docker_arch: linux/arm64
            desktop_gui: -D GUI=OFF

          - arch: ppc64le
            docker_arch: linux/ppc64le
            desktop_gui: ""
          - arch: ppc64le
            docker_arch: linux/ppc64le
            desktop_gui: -D GUI=OFF

          - arch: s390x
            docker_arch: linux/s390x
            desktop_gui: ""
          - arch: s390x
            docker_arch: linux/s390x
            desktop_gui: -D GUI=OFF

    name: ${{ matrix.name }} ${{ matrix.os_id }}:${{ matrix.os_version_id }} ${{ matrix.arch }}

    env:
      libtorrent_branch: RC_2_0 # changes which branch the git checkout command will checkout for libtorrent
      qbittorrent_branch: master # changes which branch the git checkout command will checkout for qBittorrent

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Docker multiarch bootstrap
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Create docker multiarch ${{ matrix.docker_arch }} container
        run: docker run --name multiarch -it -d -w /root -e "LANG=en_US.UTF-8" -e "DEBIAN_FRONTEND=noninteractive" --platform ${{ matrix.docker_arch }} -v ${{ github.workspace }}:/root ${{ matrix.arch }}/${{ matrix.os_id }}:${{ matrix.os_version_id }}

      - name: Run apt-get update
        run: docker exec multiarch apt-get update

      - name: Run apt-get upgrade
        run: docker exec multiarch apt-get upgrade -y

      - name: apt-get install the core build dependencies
        run: docker exec multiarch apt-get install -y build-essential curl pkg-config automake libtool git perl python3 python3-dev unzip graphviz zlib1g-dev libssl-dev libgeoip-dev cmake ninja-build

      - name: apt-get install the main qBittorrent dependencies
        run: docker exec multiarch apt-get install -y libqt5svg5-dev qtbase5-dev qttools5-dev

      - name: Bootstrap the boost files
        run: |
          boost_version="$(git ls-remote -q -t --refs https://github.com/boostorg/boost.git | awk '{sub("refs/tags/boost-", "");sub("(.*)(rc|alpha|beta)(.*)", ""); print $2 }' | awk '!/^$/' | sort -rV | head -n1)"
          curl -sNLk https://boostorg.jfrog.io/artifactory/main/release/${boost_version}/source/boost_${boost_version//./_}.tar.gz -o "boost.tar.gz"
          tar xf "boost.tar.gz"
          echo "boost_version=${boost_version//./_}" >> $GITHUB_ENV

      - name: libtorrent - git clone
        run: docker exec multiarch bash -c 'git clone --shallow-submodules --recurse-submodules https://github.com/arvidn/libtorrent.git /root/libtorrent'

      - name: libtorrent - git checkout ${{ env.libtorrent_branch }}
        run: docker exec multiarch bash -c "cd /root/libtorrent && git checkout ${{ env.libtorrent_branch }}"

      - name: libtorrent - cmake configure
        run: |
          docker exec multiarch cmake -Wno-dev -Wno-deprecated -S /root/libtorrent -G Ninja -B /root/libtorrent/build \
          -D CMAKE_BUILD_TYPE="Release" \
          -D CMAKE_CXX_STANDARD="17" \
          -D BOOST_INCLUDEDIR="/root/boost_${{ env.boost_version }}/" \
          -D CMAKE_INSTALL_PREFIX="/root/build/usr/local"

      - name: libtorrent - cmake build
        run: docker exec multiarch cmake --build /root/libtorrent/build

      - name: libtorrent - cmake install
        run: docker exec multiarch cmake --install /root/libtorrent/build

      - name: Set full libtorrent version to variable using strings
        run: echo "libtorrent_version=$(strings -d build/usr/local/lib/libtorrent-rasterbar.so | sed -rn 's|^libtorrent/(.*)|\1|p' | head -n 1)" >> $GITHUB_ENV

      - name: qbittorrent - git clone
        run: docker exec multiarch bash -c 'git clone --shallow-submodules --recurse-submodules https://github.com/qbittorrent/qBittorrent.git /root/qbittorrent'

      - name: qbittorrent - git checkout ${{ env.qbittorrent_branch }}
        run: docker exec multiarch bash -c "cd /root/qbittorrent && git checkout ${{ env.qbittorrent_branch }}"

      - name: qbittorrent cmake configure
        run: |
          docker exec multiarch cmake -Wno-dev -Wno-deprecated -S /root/qbittorrent -G Ninja -B /root/qbittorrent/build \
          -D CMAKE_BUILD_TYPE="release" \
          -D CMAKE_CXX_STANDARD="17" \
          -D CMAKE_PREFIX_PATH="/root/build/usr/local" \
          -D BOOST_INCLUDEDIR="/root/boost_${{ env.boost_version }}/" \
          ${{ matrix.desktop_gui }} \
          -D CMAKE_INSTALL_PREFIX="/root/build/usr/local"

      - name: qbittorrent cmake build
        run: docker exec multiarch cmake --build /root/qbittorrent/build

      - name: qbittorrent cmake install
        run: docker exec multiarch cmake --install /root/qbittorrent/build

      - name: Set full qBittorrent version to variable using strings
        run: echo "qbittorrent_version=$(strings -d build/usr/local/bin/${{ matrix.name }} | sed -rn 's|^qBittorrent/(.*)|\1|p' | head -n 1)" >> $GITHUB_ENV

      - name: Create deb packages
        uses: jiro4989/build-deb-action@v2
        with:
          package: "${{ matrix.name }}"
          package_root: build
          maintainer: userdocs
          version: "${{ env.qbittorrent_version }}"
          depends: "zlib1g,libgeoip1,libqt5svg5-dev,qtbase5-dev,qttools5-dev"
          arch: "${{ matrix.arch }}"
          desc: "${{ matrix.name }}-${{ matrix.arch }} for ${{ matrix.os_id }}-${{ matrix.os_version_id }}"

      - name: Remove version from release name and use hyphens
        run: mv -f "${{ matrix.name }}_${{ env.qbittorrent_version }}_${{ matrix.arch }}.deb" "${{ matrix.os_id }}-${{ matrix.os_version_id }}-${{ matrix.name }}-${{ matrix.arch }}.deb"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "${{ matrix.os_id }}-${{ matrix.os_version_id }}-${{ matrix.name }}-${{ env.qbittorrent_version }}-libtorrent-${{ env.libtorrent_version }}-${{ matrix.arch }}"
          path: "${{ matrix.os_id }}-${{ matrix.os_version_id }}-${{ matrix.name }}-${{ matrix.arch }}.deb"

      - name: "Create release - tag - assets"
        uses: ncipollo/release-action@v1.8.6
        with:
          prerelease: false
          artifacts: "${{ matrix.os_id }}-${{ matrix.os_version_id }}-${{ matrix.name }}-${{ matrix.arch }}.deb"
          replacesArtifacts: true
          tag: "${{ env.qbittorrent_version }}_${{ env.libtorrent_version }}"
          name: "qBittorrent ${{ env.qbittorrent_version }} libtorrent ${{ env.libtorrent_version }}"
          body: "qBittorrent and qBittorrent-nox built with cmake using the github master branch and the libtorrent RC_2_0 github branch on all supported arches for Debian Bullseye and Ubuntu Hirsute"
          allowUpdates: true
          token: "${{ secrets.GITHUB_TOKEN }}"
