name: test-2

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-1:
    runs-on: ${{ matrix.runs-on }}
    container: alpine:edge
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-24.04", "ubuntu-24.04-arm"]

    steps:
      - run: |
          printf '
          PRETTY_NAME="Ubuntu 24.04.1 LTS"
          NAME="Ubuntu"
          VERSION_ID="24.04"
          VERSION="24.04.1 LTS (Noble Numbat)"
          VERSION_CODENAME=noble
          ID=ubuntu
          ID_LIKE=debian
          HOME_URL="https://www.ubuntu.com/"
          SUPPORT_URL="https://help.ubuntu.com/"
          BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
          PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
          UBUNTU_CODENAME=noble
          LOGO=ubuntu-logo' > /etc/os-release

          cat /etc/os-release

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
