name: a test 8

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: windows-latest
    permissions:
      contents: read
    name: mysy2

    steps:
        - uses: actions/checkout@v4
        - uses: docker/setup-qemu-action@v3
        - uses: msys2/setup-msys2@v2
          with:
            update: true
            msystem: clangarm64
            install: >
              git curl make automake gcc
              libtool pkg-config m4
              autoconf-archive autotools
              mingw-w64-clang-aarch64-clang

