name: a test 6

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        downloads: ["true", "false"]
        versions: ["", "1.78.0", "1.84.0"]

    steps:
      - uses: userdocs/actions/boost@main
        id: boost_info
        with:
          boost_version: ${{ matrix.versions }}
          download_archive: ${{ matrix.downloads }}
          extract_archive: true

      - run: ls -la

      - run: |
          echo ${{ steps.boost_info.outputs.BOOST_FOLDER_NAME }}
          echo ${{ steps.boost_info.outputs.BOOST_ARCHIVE_NAME }}
          echo ${{ steps.boost_info.outputs.BOOST_URL }}
          echo ${{ steps.boost_info.outputs.BOOST_MAJOR_VERSION }}
          echo ${{ steps.boost_info.outputs.BOOST_MINOR_VERSION }}
          echo ${{ steps.boost_info.outputs.BOOST_PATCH_VERSION }}
