name: a test 6

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-24.04-arm
    container: ubuntu:latest
    permissions:
      contents: read
    strategy:
      matrix:
        downloads: ["true", "false"]
        versions: ["", "1.78.0", "1.84.0"]

    steps:
      - run: apt update && apt install -y git curl

      - uses: userdocs/actions/boost@main
        with:
          boost_version: ${{ matrix.versions }}
          download_archive: ${{ matrix.downloads }}
