name: a test 3

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-24.04", "ubuntu-24.04-arm"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: change file
        run: echo $(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 10) > file.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Change
          file_pattern: "file.txt"
