name: a test 2

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-24.04-arm
    container: alpine:edge
    permissions:
      contents: read
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     runs-on: ["ubuntu-24.04-arm"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: a test
        run: env

      - name: a test
        run: bash test.sh
