name: a test 6

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        boost_version: ["", "1.78.0", "1.84.0"]
        download_archive: ["true", "false"]
        extract_archive: ["true", "false"]
        working_dirs: ["", "/tmp"]

    steps:
      - uses: userdocs/actions/boost@main
        id: boost_info
        with:
          boost_version: ${{ matrix.boost_version }}
          download_archive: ${{ matrix.download_archive }}
          extract_archive: ${{ matrix.extract_archive }}
          working_dir: ${{ matrix.working_dirs }}

      - run: |
          pwd
          ls -la

      - run: |
          echo ${{ steps.boost_version_info.outputs.BOOST_WORKING_DIR }}
          echo ${{ steps.boost_version_info.outputs.BOOST_VERSION }}
          echo ${{ steps.boost_version_info.outputs.BOOST_MAJOR_VERSION }}
          echo ${{ steps.boost_version_info.outputs.BOOST_MINOR_VERSION }}
          echo ${{ steps.boost_version_info.outputs.BOOST_PATCH_VERSION }}

          echo ${{ steps.boost_version_info.outputs.BOOST_URL }}
          echo ${{ steps.boost_version_info.outputs.BOOST_ARCHIVE_NAME }}
          echo ${{ steps.boost_version_info.outputs.BOOST_FOLDER_NAME }}
          echo ${{ steps.boost_version_info.outputs.BOOST_ARCHIVE_SHA1SUM }}
          echo ${{ steps.boost_version_info.outputs.BOOST_ARCHIVE_SHA256SUM }}
