name: a test 3

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-24.04-arm"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: change file
        run: echo $(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 10) > file.txt

      - name: Commit and Push
        run: |
          git add file.txt
          git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m "Automated commit by GitHub Actions"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
