name: test-2

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-1:
    runs-on: ${{ matrix.runs-on }}
    container: alpine:edge
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-24.04", "ubuntu-24.04-arm"]

    steps:
      - run: |
          cp -f os-release /etc/os-release
          cat /etc/os-release

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
