name: a test 6

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-24.04-arm
    container: ubuntu:latest
    permissions:
      contents: read

    steps:
      - uses: userdocs/actions/boost@main
        with:
          boost_version: ""
