name: a test 4

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ${{ matrix.runs-on }}
    container: ghcr.io/userdocs/qbt-musl-cross-make-test:riscv64-linux-musl
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-24.04", "ubuntu-24.04-arm"]

    steps:
      - name: file gcc
        run: file /usr/local/bin/riscv64-linux-musl-gcc
