name: a test 7

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    name: codepspell ninja with skip dir

    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          skip: ninja/src/third_party/*
          ignore_words_list: fo,wee,addin,notin

  build-2:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    name: codepspell ninja without skip dir

    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_list: fo,wee,addin,notin
