name: a test 4

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ${{ matrix.runs-on }}
    container:
      image: ghcr.io/userdocs/qbt-musl-cross-make-test:riscv64-linux-musl
      options: --platform ${{ matrix.platform }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        include:
          - runs-on: ubuntu-24.04
            platform: linux/amd64
          - runs-on: ubuntu-24.04-arm
            platform: linux/arm64

    steps:
      - name: file gcc
        run: file /usr/local/bin/riscv64-linux-musl-gcc
