name: a test 9

on:
  workflow_dispatch:

jobs:
  arch-ubuntu:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: dpkg --print-architecture
        run: dpkg --print-architecture

      - name: uname -m
        run: uname -m

  arch-alpine:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    container:
      image: alpine:latest

    steps:
      - name: apk info --print-arch
        run: apk info --print-arch

      - name: uname -m
        run: uname -m
